export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED'
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED'

export const ADD_TASK = 'ADD_TASK'
export const REMOVE_TASK_BY_ID = 'REMOVE_TASK_BY_ID'
